package io.github.alimsrepo.navease.runtime.presentation

import androidx.navigation3.runtime.NavKey
import kotlinx.serialization.KSerializer
import kotlin.reflect.KClass

/**
 * Global registry populated by NavEase KSP-generated code.
 *
 * Holds all screens annotated with `@AutoRegister` and the app's start destination.
 * Used by the zero-configuration [NavEaseHost] overload.
 *
 * **You do not normally interact with this object directly.**
 * It is populated automatically by the KSP-generated `NavEaseAutoInit` initializer.
 *
 * On JVM-based targets (Android, Desktop), [NavEaseHost] triggers auto-discovery
 * transparently via class loading — no extra code needed in App.kt.
 *
 * On iOS/Native targets, call the KSP-generated `navEaseBootstrap()` once from your
 * platform entry point before the first composition:
 *
 * ```kotlin
 * // iosMain — MainViewController.kt
 * import io.github.alimsrepo.navease.generated.navEaseBootstrap
 *
 * fun MainViewController() = ComposeUIViewController {
 *     navEaseBootstrap()   // triggers KSP-generated initializer
 *     App()
 * }
 * ```
 *
 * `navEaseBootstrap()` is generated by KSP after the first `kspCommonMainKotlinMetadata`
 * run. On Android/JVM this call is optional.
 */
object NavEaseAutoRegistry {

    /**
     * Fully-qualified class name of the KSP-generated initializer file.
     *
     * Defaults to `io.github.alimsrepo.navease.generated.AutoRegisterScreensKt`.
     * Override only when using a custom `generatedPackage` KSP option.
     * Set it **before** first composition — e.g. inside `Application.onCreate()`.
     */
    var generatedClassHint: String =
        "io.github.alimsrepo.navease.generated.AutoRegisterScreensKt"

    internal val entries: MutableList<RegistryEntry> = mutableListOf()

    internal var startKey: NavKey? = null
        private set

    /** `true` once [entries] has been populated and [startKey] is set. */
    val isInitialized: Boolean get() = startKey != null

    /**
     * A registered screen entry produced by [addEntry].
     *
     * @property keyClass   Runtime [KClass] of the [NavKey] subtype handled by [screen].
     * @property serializer [KSerializer] for the [NavKey] subtype.
     * @property screen     [ActivityScreen] instance registered for this key.
     */
    data class RegistryEntry(
        val keyClass: KClass<*>,
        val serializer: KSerializer<*>,
        val screen: ActivityScreen<*>,
    )

    /**
     * Registers one screen into this registry.
     *
     * Called directly from the KSP-generated `NavEaseAutoInit.init {}` block when the
     * generated object is first initialised (via `navEaseBootstrap()` on iOS or via
     * class-loading on JVM).
     *
     * @param screen       Screen instance.
     * @param keyClass     Runtime [KClass] of [K].
     * @param serializer   [KSerializer] for [K].
     * @param startNavKey  Non-null to designate this entry's key as the start destination.
     */
    @Suppress("UNCHECKED_CAST")
    fun <K : NavKey> addEntry(
        screen: ActivityScreen<K>,
        keyClass: KClass<K>,
        serializer: KSerializer<K>,
        startNavKey: K? = null,
    ) {
        entries.add(
            RegistryEntry(
                keyClass   = keyClass   as KClass<*>,
                serializer = serializer as KSerializer<*>,
                screen     = screen,
            )
        )
        if (startNavKey != null) startKey = startNavKey
    }

    /**
     * Ensures the registry is populated on JVM/Android via class-loading.
     *
     * On iOS/Native this is a no-op — the registry is populated when
     * `navEaseBootstrap()` (generated) is called from the platform entry point.
     */
    internal fun ensureInitialized() {
        if (isInitialized) return
        navEaseAutoTriggerInit()
    }
}

// ── Platform hook ─────────────────────────────────────────────────────────────

/**
 * Platform-specific trigger for auto-initialising the KSP-generated registry.
 *
 * - **JVM / Android**: loads [NavEaseAutoRegistry.generatedClassHint] via `Class.forName`,
 *   which triggers the file's static initialiser and runs `NavEaseAutoInit.init {}`.
 * - **iOS / Native / JS / Wasm**: no-op. Use the KSP-generated `navEaseBootstrap()` function
 *   from your platform entry point instead.
 */
internal expect fun navEaseAutoTriggerInit()

// ── Public initialisation helpers ─────────────────────────────────────────────

/**
 * Triggers the NavEase screen registry initialisation (JVM/Android only convenience).
 *
 * On JVM/Android platforms this is equivalent to the auto-trigger that [NavEaseHost]
 * performs internally. Calling it explicitly is optional on those platforms.
 *
 * On iOS/Native/JS/Wasm this is a no-op. Use the KSP-generated `navEaseBootstrap()`
 * function from `io.github.alimsrepo.navease.generated` from your platform entry point:
 *
 * ```kotlin
 * // iosMain — MainViewController.kt
 * import io.github.alimsrepo.navease.generated.navEaseBootstrap
 *
 * fun MainViewController() = ComposeUIViewController {
 *     navEaseBootstrap()
 *     App()
 * }
 * ```
 */
fun navEaseInit() = NavEaseAutoRegistry.ensureInitialized()



