package io.github.alimsrepo.navease.runtime.presentation

import androidx.navigation3.runtime.NavKey
import kotlinx.serialization.KSerializer
import kotlin.reflect.KClass

/**
 * Global registry populated by NavEase KSP-generated code.
 *
 * Holds all screens annotated with `@AutoRegister` and the app's start destination.
 * Used by the zero-configuration [NavEaseHost] overload.
 *
 * **You do not normally interact with this object directly.**
 * It is populated automatically by the KSP-generated `NavEaseAutoInit` initializer.
 *
 * On JVM-based targets (Android, Desktop), [NavEaseHost] triggers auto-discovery
 * transparently via class loading. On other platforms (iOS, Web), initialise the
 * registry once from your platform entry point:
 *
 * ```kotlin
 * // iOS — MainViewController.kt
 * fun MainViewController() = ComposeUIViewController {
 *     navEaseInit()   // populates the registry; call before any NavEaseHost
 *     App()
 *  }
 * ```
 *
 * Alternatively use the fully typed overload which works on every platform:
 * ```kotlin
 * NavEaseHost<AppScreens>(start = AppScreens.Splash, onExitRequest = { ... }) {
 *     autoRegisterScreens()   // typed extension generated by KSP
 * }
 * ```
 */
object NavEaseAutoRegistry {

    /**
     * Fully-qualified class name of the KSP-generated initializer file.
     *
     * Defaults to `io.github.alimsrepo.navease.generated.AutoRegisterScreensKt`,
     * which matches the default `navease.generatedPackage` KSP option.
     *
     * If you use a custom `generatedPackage`, set this to
     * `"<yourPackage>.AutoRegisterScreensKt"` **before** first composition — e.g.
     * inside your `Application.onCreate()` or platform entry point.
     */
    var generatedClassHint: String =
        "io.github.alimsrepo.navease.generated.AutoRegisterScreensKt"

    /**
     * Set by the KSP-generated `NavEaseAutoInit.init {}` block via [setRegistrar].
     * Invoking this lambda registers all `@AutoRegister` screens into [entries].
     */
    internal var registrar: (() -> Unit)? = null

    internal val entries: MutableList<RegistryEntry> = mutableListOf()

    internal var startKey: NavKey? = null
        private set

    /** `true` once [entries] has been populated and [startKey] is set. */
    val isInitialized: Boolean get() = startKey != null

    /**
     * Registers the screen initializer lambda produced by KSP-generated code.
     *
     * Called from the KSP-generated `NavEaseAutoInit.init {}` block.  When the runtime
     * calls [ensureInitialized] the [init] lambda is invoked, which in turn calls
     * [addEntry] for each `@AutoRegister` screen.
     *
     * **This method is part of the NavEase internal contract and should not be called
     * from hand-written application code.**
     */
    fun setRegistrar(init: () -> Unit) {
        registrar = init
    }

    /**
     * A registered screen entry produced by [addEntry].
     *
     * @property keyClass   Runtime [KClass] of the [NavKey] subtype handled by [screen].
     * @property serializer [KSerializer] for the [NavKey] subtype.
     * @property screen     [ActivityScreen] instance registered for this key.
     */
    data class RegistryEntry(
        val keyClass: KClass<*>,
        val serializer: KSerializer<*>,
        val screen: ActivityScreen<*>,
    )

    /**
     * Registers one screen into this registry.
     * Called from the KSP-generated registrar lambda (inside `NavEaseAutoInit.init {}`).
     *
     * @param screen       Screen instance.
     * @param keyClass     Runtime [KClass] of [K].
     * @param serializer   [KSerializer] for [K].
     * @param startNavKey  Non-null to designate this entry's key as the start destination.
     */
    @Suppress("UNCHECKED_CAST")
    fun <K : NavKey> addEntry(
        screen: ActivityScreen<K>,
        keyClass: KClass<K>,
        serializer: KSerializer<K>,
        startNavKey: K? = null,
    ) {
        entries.add(
            RegistryEntry(
                keyClass  = keyClass  as KClass<*>,
                serializer = serializer as KSerializer<*>,
                screen    = screen,
            )
        )
        if (startNavKey != null) startKey = startNavKey
    }

    /**
     * Ensures the registry is populated.
     *
     * On JVM-based platforms calls the platform hook [navEaseAutoTriggerInit] which
     * loads the KSP-generated class via reflection, triggering its static initialiser.
     * On other platforms this function is a no-op — call [navEaseInit] explicitly from
     * your platform entry point.
     */
    internal fun ensureInitialized() {
        if (isInitialized) return
        // Platform hook: JVM loads the generated class; other platforms are no-ops.
        navEaseAutoTriggerInit()
        // Invoke the registrar set by NavEaseAutoInit.init {}
        registrar?.invoke()
    }
}

// ── Platform hook ─────────────────────────────────────────────────────────────

/**
 * Platform-specific trigger for auto-initialising the KSP-generated registry.
 *
 * - **JVM / Android**: loads [NavEaseAutoRegistry.generatedClassHint] via `Class.forName`,
 *   which triggers the file's static initialiser and runs `NavEaseAutoInit.init {}`.
 * - **Other platforms**: no-op — rely on [navEaseInit] or the typed [NavEaseHost] overload.
 */
internal expect fun navEaseAutoTriggerInit()

// ── Public initialisation helper ──────────────────────────────────────────────

/**
 * Manually initialises the NavEase screen registry.
 *
 * Call this **once** before the first [NavEaseHost] composition on non-JVM targets
 * (iOS, Desktop, Web). On JVM/Android, [NavEaseHost] triggers initialisation
 * automatically and this call is optional.
 *
 * ```kotlin
 * // iOS — MainViewController.kt:
 * fun MainViewController() = ComposeUIViewController {
 *     navEaseInit()
 *     App()
 * }
 * ```
 */
fun navEaseInit() = NavEaseAutoRegistry.ensureInitialized()



