package io.github.alimsrepo.navease.ksp

/**
 * Emits the two generated files. Pure string building — no KSP types — so the output can be
 * unit-tested without running a compilation.
 */
internal object NavEaseCodegen {

    const val HOST_PACKAGE = "io.github.alimsrepo.navease.runtime.host"

    private const val REGISTRY = "io.github.alimsrepo.navease.runtime.registry.NavEaseAutoRegistry"
    private const val SERIALIZATION = "kotlinx.serialization"
    private const val CONTROLLER = "io.github.alimsrepo.navease.runtime.navigation.NavEaseController"
    private const val NAV_KEY = "io.github.alimsrepo.navease.internal.runtime.NavKey"
    private const val TRANSITION = "io.github.alimsrepo.navease.runtime.transition.NavTransition"

    /** File name for the host overloads. The package is fixed, so the name carries the module. */
    fun hostOverloadsFileName(generatedPackage: String): String =
        "NavEaseHostOverloads_${generatedPackage.toIdentifier()}"

    /**
     * `AutoRegisterScreens.kt` — a `KSerializer` per key plus `navEaseBootstrap()`.
     *
     * [entries] must already be sorted; the caller owns ordering so that the output is
     * byte-identical between builds.
     */
    fun autoRegisterScreens(generatedPackage: String, entries: List<ScreenEntry>): String =
        buildString {
            appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
            appendLine()
            appendLine("package $generatedPackage")
            appendLine()
            appendLine("// Generated by NavEase KSP. Do not edit.")
            appendLine("//")
            appendLine("// Names are fully qualified on purpose: two sealed roots may each declare a")
            appendLine("// key of the same simple name, and imports could not tell them apart.")
            appendLine()
            entries.forEach { entry ->
                appendLine(serializer(entry))
                appendLine()
            }
            appendLine("private object NavEaseAutoInit {")
            appendLine("    init {")
            entries.forEach { entry ->
                appendLine(
                    "        $REGISTRY.addEntry(${entry.keyFqn}::class, ${entry.rootFqn}::class, " +
                        "${entry.serializerName}) { ${entry.screenFqn}() }",
                )
            }
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("/**")
            appendLine(" * Registers every @AutoRegister screen in this module.")
            appendLine(" *")
            appendLine(" * Called by the generated NavEaseHost overloads before a host composes.")
            appendLine(" * Idempotent, and safe to call from application startup as well.")
            appendLine(" */")
            appendLine("public fun navEaseBootstrap() {")
            appendLine("    NavEaseAutoInit")
            appendLine("}")
        }

    /**
     * A `KSerializer` for one key, so users never annotate their keys with `@Serializable`.
     *
     * Unknown elements are skipped rather than rejected, so a back stack written by an older
     * build still restores after a parameter is removed. A *missing* element is reported by
     * name: NavEase always writes every parameter, so one can only go missing when the key's
     * parameters changed between the save and the restore.
     */
    fun serializer(entry: ScreenEntry): String = buildString {
        val name = entry.serializerName
        val key = entry.keyFqn
        val params = entry.keyParams

        if (params.isEmpty()) {
            appendLine("private object $name : $SERIALIZATION.KSerializer<$key> {")
            appendLine(
                "    override val descriptor = " +
                    "$SERIALIZATION.descriptors.buildClassSerialDescriptor(\"$key\")",
            )
            appendLine(
                "    override fun serialize(encoder: $SERIALIZATION.encoding.Encoder, value: $key) {",
            )
            appendLine("        encoder.beginStructure(descriptor).endStructure(descriptor)")
            appendLine("    }")
            appendLine(
                "    override fun deserialize(decoder: $SERIALIZATION.encoding.Decoder): $key {",
            )
            appendLine("        decoder.beginStructure(descriptor).endStructure(descriptor)")
            appendLine("        return $key")
            appendLine("    }")
            append("}")
            return@buildString
        }

        appendLine("@Suppress(\"UNCHECKED_CAST\")")
        appendLine("private object $name : $SERIALIZATION.KSerializer<$key> {")
        params.forEachIndexed { i, p ->
            appendLine(
                "    private val f$i = $SERIALIZATION.serializer(kotlin.reflect.typeOf<${p.type}>()) " +
                    "as $SERIALIZATION.KSerializer<${p.type}>",
            )
        }
        appendLine(
            "    override val descriptor = " +
                "$SERIALIZATION.descriptors.buildClassSerialDescriptor(\"$key\") {",
        )
        params.forEachIndexed { i, p -> appendLine("        element(\"${p.name}\", f$i.descriptor)") }
        appendLine("    }")

        appendLine(
            "    override fun serialize(encoder: $SERIALIZATION.encoding.Encoder, value: $key) {",
        )
        appendLine("        val out = encoder.beginStructure(descriptor)")
        params.forEachIndexed { i, p ->
            appendLine("        out.encodeSerializableElement(descriptor, $i, f$i, value.${p.name})")
        }
        appendLine("        out.endStructure(descriptor)")
        appendLine("    }")

        appendLine("    override fun deserialize(decoder: $SERIALIZATION.encoding.Decoder): $key {")
        params.indices.forEach { i -> appendLine("        var v$i: Any? = null") }
        params.indices.forEach { i -> appendLine("        var seen$i = false") }
        appendLine("        val input = decoder.beginStructure(descriptor)")
        appendLine("        loop@ while (true) {")
        appendLine("            when (val index = input.decodeElementIndex(descriptor)) {")
        params.indices.forEach { i ->
            appendLine(
                "                $i -> { v$i = input.decodeSerializableElement(descriptor, $i, f$i); " +
                    "seen$i = true }",
            )
        }
        appendLine("                $SERIALIZATION.encoding.CompositeDecoder.DECODE_DONE -> break@loop")
        appendLine(
            "                $SERIALIZATION.encoding.CompositeDecoder.UNKNOWN_NAME -> continue@loop",
        )
        appendLine("                else -> throw $SERIALIZATION.SerializationException(")
        appendLine("                    \"NavEase: unexpected element index \$index while decoding $key\"")
        appendLine("                )")
        appendLine("            }")
        appendLine("        }")
        appendLine("        input.endStructure(descriptor)")
        params.forEachIndexed { i, p ->
            appendLine("        if (!seen$i) throw $SERIALIZATION.SerializationException(")
            appendLine(
                "            \"NavEase: parameter '${p.name}' is missing while restoring $key. The " +
                    "saved back stack was written when this key had different parameters.\"",
            )
            appendLine("        )")
        }
        val args = params.mapIndexed { i, p -> "${p.name} = v$i as ${p.type}" }.joinToString(", ")
        appendLine("        return $key($args)")
        appendLine("    }")
        append("}")
    }

    /**
     * `NavEaseHostOverloads_<module>.kt` — one `NavEaseHost` overload per sealed root.
     *
     * The overloads live in the runtime's host package so that an ordinary
     * `import io.github.alimsrepo.navease.runtime.host.NavEaseHost` picks them up. Each is
     * more specific than the runtime's generic declaration, so a call naming a known root
     * binds here and initialises the registry before the host composes.
     */
    fun hostOverloads(generatedPackage: String, entries: List<ScreenEntry>): String {
        val roots = entries.map { it.rootFqn }.distinct().sorted()
        return buildString {
            appendLine("package $HOST_PACKAGE")
            appendLine()
            appendLine("// Generated by NavEase KSP. Do not edit.")
            appendLine("//")
            appendLine("// These overloads deliberately live in the runtime's host package so that an")
            appendLine("// ordinary NavEaseHost import picks them up. Each is more specific than the")
            appendLine("// runtime's generic NavEaseHost, so a call naming a known root binds here and")
            appendLine("// the screen registry is initialised first.")
            roots.forEach { root ->
                appendLine()
                appendLine("/** Host for every @AutoRegister screen under [$root]. */")
                appendLine("@androidx.compose.runtime.Composable")
                appendLine("public inline fun <reified T : $root> NavEaseHost(")
                appendLine("    start: $root,")
                appendLine("    noinline onExitRequest: () -> Unit = {},")
                appendLine("    enableSharedTransitions: Boolean = false,")
                appendLine("    navTransition: $TRANSITION = $TRANSITION.Push,")
                appendLine("    noinline onDestinationChanged: ($CONTROLLER.($NAV_KEY) -> Unit)? = null,")
                appendLine(") {")
                appendLine("    $generatedPackage.navEaseBootstrap()")
                appendLine("    NavEaseHostForRoot(")
                appendLine("        rootClass = $root::class,")
                appendLine("        start = start,")
                appendLine("        onExitRequest = onExitRequest,")
                appendLine("        enableSharedTransitions = enableSharedTransitions,")
                appendLine("        navTransition = navTransition,")
                appendLine("        onDestinationChanged = onDestinationChanged,")
                appendLine("    )")
                appendLine("}")
            }
        }
    }
}
