package com.alim.navease

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.material3.MaterialTheme
import io.github.alimsrepo.navease.generated.NavEaseHost

// Import all screen composables so KSP picks them up during compilation
import com.alim.navease.screens.SplashScreen
import com.alim.navease.screens.HomeScreen
import com.alim.navease.screens.DetailScreen
import com.alim.navease.screens.SettingsScreen

/**
 * Sample application entry point.
 *
 * [NavEaseHost] is auto-generated by the NavEase KSP processor — it wires together
 * all `@NavEaseScreen`-annotated composables discovered at compile time.
 *
 * Run `./gradlew :androidApp:kspDebugKotlin` once to generate the factory, then build normally.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        enableEdgeToEdge()
        super.onCreate(savedInstanceState)

        setContent {
            MaterialTheme {
                NavEaseHost(
                    startDestination = AppScreens.Splash,
                    // Flip to true to see the live back-stack overlay
                    debugOverlay = BuildConfig.DEBUG,
                )
            }
        }
    }
}


