package com.alim.navease

import androidx.compose.ui.window.ComposeUIViewController
import com.alim.navease.screens.App
import io.github.alimsrepo.navease.generated.navEaseBootstrap

/**
 * iOS entry point for the NavEase sample app.
 *
 * [navEaseBootstrap] triggers the KSP-generated [NavEaseAutoInit] object, which registers
 * all @AutoRegister screens into [NavEaseAutoRegistry] before the first composition.
 *
 * On Android/JVM this call is not needed — screens are discovered automatically via
 * class loading when [NavEaseHost] first composes.
 *
 * `navEaseBootstrap` is generated by KSP. Run `./gradlew :shared:kspCommonMainKotlinMetadata`
 * once if the import shows as unresolved.
 */
fun MainViewController() = ComposeUIViewController {
    navEaseBootstrap()
    App()
}
